# Generated by Django 4.2 on 2023-05-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupal4', '0002_alter_proveedor_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
